### ISSUE TITLE
[Bug]:  yojenkins fails if there's no history file, which you don't have the first time you run it

### ISSUE THREAD

**Issue by cosmoselodie** [ismet55555/yojenkins#117]
### What happened?

While I appreciate history files I don't think not having one should prevent you from running the software.   The code below here is failing for me on a fresh install because the history file doesn't exist.  It's the load_content_from_local file call that's hitting a 'fail_out' when the file doesn't exist.  To use yojenkins for the first time (to even run configure) you have to make these directories and touch this file or maybe there's something somewhere else that does it.  

Fwiw, I think the conditional below "if not contents" is a bit aggressive too.  

My thoughts are:
- if history isn't there, print a warning to the logs or something and then make the directories and make the file
- if history has an issue loading it's contents, print a warning but let the user carry on

Not sure if my boss will give me the time to implement this fix on your behalf but we were trying out the tool yesterday - which despite it's alpha-ness is WAYYYYYY better than the jenkins java based cli.  Anyways, hope this helps.

127 def history(profile: str, clear: bool) -> None:
128     """Displaying the command history and clearing the history file if requested.
129
130     # TODO: Ability to clear only for a specific profile.
131
132     Args:
133         profile (str): The name of the profile to to filter history with
134         clear (bool):  Clearing the history file
135
136     Returns:
137         None
138     """
139     # Load contents from history file
140     history_file_path = os.path.join(os.path.join(Path.home(), cu.CONFIG_DIR_NAME), cu.HISTORY    _FILE_NAME)
141     contents = load_contents_from_local_file('json', history_file_path)
142     if not contents:
143         click.secho('No history found', fg='bright_red', bold=True)
144         sys.exit(1)

My output that led me here: 

 yojenkins auth configure                                                      1826ms  Thu 09:49
 Failed to find file: /home/ccosmos/.yojenkins/history

that's on the latest 0.0.67

### How can we reproduce this?

fresh install, wipe ~/.yojenkins, run yojenkins auth configure

### Command `--debug` output

ss

### Version of `yojenkins`

0.0.67

### Where was `yojenkins` run in relation to the Jenkins server?

Locally

### Was the Jenkins server containerized?

No

### Which operating systems were you using when this happened?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

### How is your day going?

Meh

**Comment by ismet55555** [comment]
Hey thank you for the bug report. Great catch actually, this is pretty critical.
Thank you also for the quick suggestion. I will address it shortly.

**Comment by ismet55555** [comment]
Thank you @kwmlodozeniec !
