### ISSUE TITLE
[Feature-Request]: Allow use of existing token

### ISSUE THREAD

**Issue by cosmoselodie** [ismet55555/yojenkins#118]
### Describe the feature you would like to see

Hey - i might not have been able to figure out how to do this but I wanted to use an existing token.  There is the json-file way to do it, I guess there's that - but you have to make this syntax heavy file to then import your credentials.  I think it'd be nice if you could just put your own in if it already exists.  I found a workaround to this which was to hack an existing .yojenkins profiles/credentials file and add my key that way.

### Describe alternatives/workarounds you have considered

hi the work around is in the description.

### Which operating systems are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Other
- [ ] I don't know

**Comment by ismet55555** [comment]
This seems to be a duplicate from #119. I will close this issue and keep the other one.
