### ISSUE TITLE
[Feature-Request]: WBN if you could provide credentials on the command line for automation and not install anything to $HOME

### ISSUE THREAD

**Issue by cosmoselodie** [ismet55555/yojenkins#119]
### Describe the feature you would like to see

hi - I was trying to imagine how to use yojenkins in automation as the json output is pretty nice.  I'd need to be able to pip install yojenkins and then grab a token from a cloud based secret manager and setup yojenkins for every single job we run as they're all sandboxed.  Right now I could do all that and bake stuff into a json file - but that configuration file ultimately has to install to home (afaik).  It'd be nice to be able to run jenkins with no pre-configuration or files stored anywhere that could impact other processes running as our automation user. 

With the jenkins java cli I have the option to put my token on the command line when I run it - something like that would allow the workflow I described.

### Describe alternatives/workarounds you have considered

Because the auth system writes to /home for the given user it's a no go for the type of automation I'm working with at this time.

### Which operating systems are you using?

- [X] macOS
- [X] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

**Comment by ismet55555** [comment]
Thank you for your feature request. I can see what you mean. I will look into it shortly.

**Comment by ismet55555** [comment]
If possible, can you provide an example of what a command would look like with this feature?

I'm guessing without credential file locally, you would have to specify all info in the command, something like this?
```
yojenkins build info my-job --latest --auth https://my-server.com,my-username,55fg9cb61d34edfe83f82763cf8879c70v
```

Or whatever formatting, maybe JSON as a string:
```
yojenkins build info my-job --latest --auth '{"jenkins_server_url": "https://my-server.com", "username", "my-username", "api-token": "11fb9cb61d34edfe73f82763cf8879c79a"}'
```

Or maybe you would be able to provide your own credentials file. In your case, you'd have to do some work to inject the token value into a template credential file, then specify that path in the command.
```
yojenkins build info my-job --latest --auth-file /path/to/custom/credential/file
```

**Comment by ismet55555** [comment]
Please see PR #126 for a summary of changes.  I think you will be able to use that for what you want to accomplish. Thank you again for the suggestion.
