### ISSUE TITLE
[Feature-Request]: Simple way to replay a job with the same parameter as the last time it was run

### ISSUE THREAD

**Issue by mdiez-modus** [ismet55555/yojenkins#148]
### Describe the feature you would like to see

it would be great if we had something like

yojenkins build rebuild URL

it should trigger a new build from the job of URL using the parameters from the last build (have it failed or not)
also, it should show the output (with --follow) on the console.

that would be the ultimate tool to test jenkinsfiles!

### Describe alternatives/workarounds you have considered

writing a PR

### Which operating systems are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

### How is your day going?

Not bad

**Comment by ismet55555** [comment]
Thanks for the request. Not a bad idea. I like it. Let me look into it. I will keep you updated

**Comment by ismet55555** [comment]
Re-opening this feature request. I will start work on your --follow feature for commands, possibly a waiting sign/spinner/symbol.  (As discussed during the conference). Thanks for the follow-up and reminder!

**Comment by ismet55555** [comment]
@marcosdiez Thank you so much for your contribution. I just released a version which includes your changes.
