### ISSUE TITLE
[Bug]: simpleaudio is mandatory requirement

### ISSUE THREAD

**Issue by gaborbernat** [ismet55555/yojenkins#192]
### What happened?

It seems it's not possible to install this package without simpleaudio...

### How can we reproduce this?

N.A.

### Version of `yojenkins`

latest

### Where was `yojenkins` run in relation to the Jenkins server?

Locally

### Was the Jenkins server containerized?

Yes

### Which operating systems were you using when this happened?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

### How is your day going?

None

**Comment by ismet55555** [comment]
Hey thank you for the issue. Just to clarify, you want the ability to install `yojenkins` without any of the audio features, or have it optional?

You are right, as of right now, it will want to install `simpleaudio`, which in some settings, such as scripting, may not be desirable.

**Comment by ismet55555** [comment]
I'm reopening since it's a great suggestion
