### ISSUE TITLE
[Bug]: History file corruption

### ISSUE THREAD

**Issue by bartlibert** [ismet55555/yojenkins#219]
### What happened?

I regularly see corruption of the history file. I have no exact reproduction scenario, but what I do is, I have a script running every 30 minutes that first runs`yojenkins server reachable` and then `yojenkins server info` (which I then parse with jq to show some information in waybar).

The corruption prevents yojenkins from starting up, with error `Failed to load specified local .json file:`.

The corruption is not always the same. What I have observed:
- An extra '}' at the end
- The first couple of entries are within an array in an object, and after that a new object with a new array is started
- Entire batches of null bytes in the file

It could be that two instances are writing in parallel, but I'm not sure about that, as I also have seen the issue while only one script is running.

### How can we reproduce this?

No real scenario unfortunately. Running `yojenkins server reachable` and `yojenkins server info` in a script every 30 minutes seems to cause if for me.

### Version of `yojenkins`

0.0.85

### Where was `yojenkins` run in relation to the Jenkins server?

Remotely

### Was the Jenkins server containerized?

No

### Which operating systems were you using when this happened?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

### How is your day going?

Not bad

**Comment by ismet55555** [comment]
Thank you for bringing this up in such a detailed way! I am looking at it now.

**Comment by ismet55555** [comment]
Please let me know if that history file issue happens again. Thank you.
